[package]
name = "astra_lite"
version = "0.0.1"
edition = "2021"
description = "Software for deepsky astrophotography"
repository = "https://github.com/art-den/astra_lite"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.15"
anyhow = "1.0"
fitsio = "*"
libc = "*"
bitstream-io = "1.3"
itertools = "0.10"
tiff = "0.8"
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1"
regex = "1.7"
xmltree = "0.10"
dirs = "4.0"
bitflags = "1.3"
log = "0.4"
flexi_logger = "0.24"
chrono = "0.4"

[profile.dev]
opt-level = 1
panic = "abort"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"

[profile.profiling]
inherits = "release"
debug = true
strip = false
panic = "abort"

[profile.dev.package."*"]
opt-level = 1
