# Configuration for cross utility (https://github.com/cross-rs/cross)

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata",
    "apt-get install -y libgtk-3-dev:$CROSS_DEB_ARCH dpkg dpkg-dev"
]

[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata",
    "apt-get install -y libgtk-3-dev:$CROSS_DEB_ARCH dpkg dpkg-dev"
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata",
    "apt-get install -y libgtk-3-dev:$CROSS_DEB_ARCH dpkg dpkg-dev"
]
